-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--

-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_contact_summary`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_contact_summary
-- *
-- * Layouts for the contact summary page
-- *
-- *******************************************************/
CREATE TABLE `civicrm_contact_summary` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique ContactSummary ID',
     `contact_type` varchar(255)    COMMENT 'The type of contacts this layout applies to.',
     `contact_sub_type` varchar(255)    COMMENT 'The contacts subtypes this layout applies to.',
     `groups` varchar(255)    COMMENT 'Show layout to users belonging to these groups.',
     `weight` int    ,
     `data` longtext    COMMENT 'Contains json encoded layout blocks' 
,
        PRIMARY KEY (`id`)
 
 
 
)    ;

 
